export const menuResources = {
  en: {
    file: 'File',
    edit: 'Edit',
    view: 'View',
    quit: 'Quit',
    undo: 'Undo',
    redo: 'Redo',
    cut: 'Cut',
    copy: 'Copy',
    paste: 'Paste',
    selectAll: 'Select all',
    resetZoom: 'Actual size',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    togglefullscreen: 'Full screen',
  },
  ru: {
    file: 'Файл',
    edit: 'Правка',
    view: 'Вид',
    quit: 'Выход',
    undo: 'Отменить',
    redo: 'Повторить',
    cut: 'Вырезать',
    copy: 'Копировать',
    paste: 'Вставить',
    selectAll: 'Выделить всё',
    resetZoom: 'Исходный масштаб',
    zoomIn: 'Увеличить',
    zoomOut: 'Уменьшить',
    togglefullscreen: 'Полный экран',
  },
};
